import '@/app/globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'ORM Prisma - Relation 1:N',
  description: 'Generated by create next app',
  manifest: '/manifest.json'
}

export default function RootLayout({children}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Navbar />
        <main> {children} </main> 
        <Footer />      
      </body>
    </html>
  )
}
